// Tunisia Governorates and Delegations data for JAX Delivery
// Based on the 24 governorates of Tunisia

export interface Delegation {
  id: number;
  name: string;
}

export interface Governorate {
  id: number;
  name: string;
  delegations: Delegation[];
}

export const TUNISIA_GOVERNORATES: Governorate[] = [
  {
    id: 1,
    name: "Tunis",
    delegations: [
      { id: 1, name: "Tunis Ville" },
      { id: 2, name: "Le Bardo" },
      { id: 3, name: "Le Kram" },
      { id: 4, name: "La Goulette" },
      { id: 5, name: "Carthage" },
      { id: 6, name: "Sidi Bou Said" },
      { id: 7, name: "La Marsa" },
      { id: 8, name: "Sidi Hassine" },
      { id: 9, name: "El Ouardia" },
      { id: 10, name: "El Kabaria" },
      { id: 11, name: "Ezzouhour" },
      { id: 12, name: "El Hrairia" },
      { id: 13, name: "Bab El Bhar" },
      { id: 14, name: "Bab Souika" },
      { id: 15, name: "El Omrane" },
      { id: 16, name: "El Omrane Superieur" },
      { id: 17, name: "Ettahrir" },
      { id: 18, name: "El Menzah" },
      { id: 19, name: "Cite El Khadra" },
      { id: 20, name: "El Manar" },
      { id: 21, name: "Djebel Jelloud" },
    ],
  },
  {
    id: 2,
    name: "Ariana",
    delegations: [
      { id: 1, name: "Ariana Ville" },
      { id: 2, name: "La Soukra" },
      { id: 3, name: "Raoued" },
      { id: 4, name: "Kalaat El Andalous" },
      { id: 5, name: "Sidi Thabet" },
      { id: 6, name: "Ettadhamen" },
      { id: 7, name: "Mnihla" },
    ],
  },
  {
    id: 3,
    name: "Ben Arous",
    delegations: [
      { id: 1, name: "Ben Arous" },
      { id: 2, name: "La Nouvelle Medina" },
      { id: 3, name: "El Mourouj" },
      { id: 4, name: "Hammam Lif" },
      { id: 5, name: "Hammam Chott" },
      { id: 6, name: "Bou Mhel El Bassatine" },
      { id: 7, name: "Ezzahra" },
      { id: 8, name: "Rades" },
      { id: 9, name: "Megrine" },
      { id: 10, name: "Mohamedia" },
      { id: 11, name: "Fouchana" },
      { id: 12, name: "Mornag" },
    ],
  },
  {
    id: 4,
    name: "Manouba",
    delegations: [
      { id: 1, name: "Manouba" },
      { id: 2, name: "Den Den" },
      { id: 3, name: "Douar Hicher" },
      { id: 4, name: "Oued Ellil" },
      { id: 5, name: "Mornaguia" },
      { id: 6, name: "Borj El Amri" },
      { id: 7, name: "Djedeida" },
      { id: 8, name: "Tebourba" },
      { id: 9, name: "El Battan" },
    ],
  },
  {
    id: 5,
    name: "Bizerte",
    delegations: [
      { id: 1, name: "Bizerte Nord" },
      { id: 2, name: "Bizerte Sud" },
      { id: 3, name: "Sejnane" },
      { id: 4, name: "Joumine" },
      { id: 5, name: "Mateur" },
      { id: 6, name: "Ghezala" },
      { id: 7, name: "Menzel Bourguiba" },
      { id: 8, name: "Tinja" },
      { id: 9, name: "Utique" },
      { id: 10, name: "Ghar El Melh" },
      { id: 11, name: "Menzel Jemil" },
      { id: 12, name: "El Alia" },
      { id: 13, name: "Ras Jebel" },
      { id: 14, name: "Rafraf" },
    ],
  },
  {
    id: 6,
    name: "Beja",
    delegations: [
      { id: 1, name: "Beja Nord" },
      { id: 2, name: "Beja Sud" },
      { id: 3, name: "Amdoun" },
      { id: 4, name: "Nefza" },
      { id: 5, name: "Teboursouk" },
      { id: 6, name: "Testour" },
      { id: 7, name: "Goubellat" },
      { id: 8, name: "Mejez El Bab" },
      { id: 9, name: "Thibar" },
    ],
  },
  {
    id: 7,
    name: "Jendouba",
    delegations: [
      { id: 1, name: "Jendouba" },
      { id: 2, name: "Jendouba Nord" },
      { id: 3, name: "Bou Salem" },
      { id: 4, name: "Tabarka" },
      { id: 5, name: "Ain Draham" },
      { id: 6, name: "Fernana" },
      { id: 7, name: "Ghardimaou" },
      { id: 8, name: "Oued Meliz" },
      { id: 9, name: "Balta Bou Aouane" },
    ],
  },
  {
    id: 8,
    name: "Le Kef",
    delegations: [
      { id: 1, name: "Le Kef Ouest" },
      { id: 2, name: "Le Kef Est" },
      { id: 3, name: "Nebeur" },
      { id: 4, name: "Sakiet Sidi Youssef" },
      { id: 5, name: "Tajerouine" },
      { id: 6, name: "Kalaat Senan" },
      { id: 7, name: "Kalaat Khasba" },
      { id: 8, name: "Djerissa" },
      { id: 9, name: "El Ksour" },
      { id: 10, name: "Dahmani" },
      { id: 11, name: "Sers" },
    ],
  },
  {
    id: 9,
    name: "Siliana",
    delegations: [
      { id: 1, name: "Siliana Nord" },
      { id: 2, name: "Siliana Sud" },
      { id: 3, name: "Bou Arada" },
      { id: 4, name: "Gaafour" },
      { id: 5, name: "El Krib" },
      { id: 6, name: "Sidi Bou Rouis" },
      { id: 7, name: "Maktar" },
      { id: 8, name: "Rouhia" },
      { id: 9, name: "Kesra" },
      { id: 10, name: "Bargou" },
      { id: 11, name: "El Aroussa" },
    ],
  },
  {
    id: 10,
    name: "Nabeul",
    delegations: [
      { id: 1, name: "Nabeul" },
      { id: 2, name: "Dar Chaabane El Fehri" },
      { id: 3, name: "Beni Khiar" },
      { id: 4, name: "El Mida" },
      { id: 5, name: "Korba" },
      { id: 6, name: "Menzel Temime" },
      { id: 7, name: "El Haouaria" },
      { id: 8, name: "Takelsa" },
      { id: 9, name: "Soliman" },
      { id: 10, name: "Menzel Bouzelfa" },
      { id: 11, name: "Beni Khalled" },
      { id: 12, name: "Grombalia" },
      { id: 13, name: "Bouargoub" },
      { id: 14, name: "Hammamet" },
      { id: 15, name: "Kelibia" },
      { id: 16, name: "Hammam Ghezaz" },
    ],
  },
  {
    id: 11,
    name: "Zaghouan",
    delegations: [
      { id: 1, name: "Zaghouan" },
      { id: 2, name: "Zriba" },
      { id: 3, name: "Bir Mcherga" },
      { id: 4, name: "Djebel El Oust" },
      { id: 5, name: "El Fahs" },
      { id: 6, name: "Nadhour" },
    ],
  },
  {
    id: 12,
    name: "Sousse",
    delegations: [
      { id: 1, name: "Sousse Ville" },
      { id: 2, name: "Sousse Jawhara" },
      { id: 3, name: "Sousse Riadh" },
      { id: 4, name: "Sousse Sidi Abdelhamid" },
      { id: 5, name: "Hammam Sousse" },
      { id: 6, name: "Akouda" },
      { id: 7, name: "Kalaa Kebira" },
      { id: 8, name: "Sidi Bou Ali" },
      { id: 9, name: "Hergla" },
      { id: 10, name: "Enfidha" },
      { id: 11, name: "Bouficha" },
      { id: 12, name: "Kondar" },
      { id: 13, name: "Sidi El Heni" },
      { id: 14, name: "Msaken" },
      { id: 15, name: "Kalaa Sghira" },
    ],
  },
  {
    id: 13,
    name: "Monastir",
    delegations: [
      { id: 1, name: "Monastir" },
      { id: 2, name: "Ouerdanine" },
      { id: 3, name: "Sahline" },
      { id: 4, name: "Zeramdine" },
      { id: 5, name: "Beni Hassen" },
      { id: 6, name: "Jemmal" },
      { id: 7, name: "Bembla" },
      { id: 8, name: "Moknine" },
      { id: 9, name: "Bekalta" },
      { id: 10, name: "Teboulba" },
      { id: 11, name: "Ksar Hellal" },
      { id: 12, name: "Ksibet El Mediouni" },
      { id: 13, name: "Sayada Lamta Bou Hjar" },
    ],
  },
  {
    id: 14,
    name: "Mahdia",
    delegations: [
      { id: 1, name: "Mahdia" },
      { id: 2, name: "Bou Merdes" },
      { id: 3, name: "Ouled Chamekh" },
      { id: 4, name: "Chorbane" },
      { id: 5, name: "Hebira" },
      { id: 6, name: "Essouassi" },
      { id: 7, name: "El Jem" },
      { id: 8, name: "Chebba" },
      { id: 9, name: "Melloulech" },
      { id: 10, name: "Sidi Alouane" },
      { id: 11, name: "Ksour Essef" },
    ],
  },
  {
    id: 15,
    name: "Sfax",
    delegations: [
      { id: 1, name: "Sfax Ville" },
      { id: 2, name: "Sfax Ouest" },
      { id: 3, name: "Sfax Sud" },
      { id: 4, name: "Sakiet Ezzit" },
      { id: 5, name: "Sakiet Eddaier" },
      { id: 6, name: "Thyna" },
      { id: 7, name: "El Amra" },
      { id: 8, name: "Agareb" },
      { id: 9, name: "Jebeniana" },
      { id: 10, name: "El Hencha" },
      { id: 11, name: "Menzel Chaker" },
      { id: 12, name: "Ghraiba" },
      { id: 13, name: "Bir Ali Ben Khalifa" },
      { id: 14, name: "Skhira" },
      { id: 15, name: "Mahares" },
      { id: 16, name: "Kerkennah" },
    ],
  },
  {
    id: 16,
    name: "Kairouan",
    delegations: [
      { id: 1, name: "Kairouan Nord" },
      { id: 2, name: "Kairouan Sud" },
      { id: 3, name: "Chebika" },
      { id: 4, name: "Sbikha" },
      { id: 5, name: "Haffouz" },
      { id: 6, name: "Ala" },
      { id: 7, name: "Hajeb El Ayoun" },
      { id: 8, name: "Nasrallah" },
      { id: 9, name: "Chrarda" },
      { id: 10, name: "Bouhajla" },
      { id: 11, name: "El Oueslatia" },
    ],
  },
  {
    id: 17,
    name: "Kasserine",
    delegations: [
      { id: 1, name: "Kasserine Nord" },
      { id: 2, name: "Kasserine Sud" },
      { id: 3, name: "Ezzouhour" },
      { id: 4, name: "Hassi El Ferid" },
      { id: 5, name: "Sbeitla" },
      { id: 6, name: "Sbiba" },
      { id: 7, name: "Djedeliane" },
      { id: 8, name: "El Ayoun" },
      { id: 9, name: "Thala" },
      { id: 10, name: "Hidra" },
      { id: 11, name: "Foussana" },
      { id: 12, name: "Feriana" },
      { id: 13, name: "Majel Bel Abbes" },
    ],
  },
  {
    id: 18,
    name: "Sidi Bouzid",
    delegations: [
      { id: 1, name: "Sidi Bouzid Ouest" },
      { id: 2, name: "Sidi Bouzid Est" },
      { id: 3, name: "Jilma" },
      { id: 4, name: "Cebbala Ouled Asker" },
      { id: 5, name: "Bir El Hafey" },
      { id: 6, name: "Sidi Ali Ben Aoun" },
      { id: 7, name: "Menzel Bouzaiane" },
      { id: 8, name: "Meknassy" },
      { id: 9, name: "Souk Jedid" },
      { id: 10, name: "Mezzouna" },
      { id: 11, name: "Regueb" },
      { id: 12, name: "Ouled Haffouz" },
    ],
  },
  {
    id: 19,
    name: "Gabes",
    delegations: [
      { id: 1, name: "Gabes Ville" },
      { id: 2, name: "Gabes Ouest" },
      { id: 3, name: "Gabes Sud" },
      { id: 4, name: "Ghannouch" },
      { id: 5, name: "Metouia" },
      { id: 6, name: "Menzel El Habib" },
      { id: 7, name: "El Hamma" },
      { id: 8, name: "Matmata" },
      { id: 9, name: "Nouvelle Matmata" },
      { id: 10, name: "Mareth" },
    ],
  },
  {
    id: 20,
    name: "Medenine",
    delegations: [
      { id: 1, name: "Medenine Nord" },
      { id: 2, name: "Medenine Sud" },
      { id: 3, name: "Beni Khedache" },
      { id: 4, name: "Ben Guerdane" },
      { id: 5, name: "Zarzis" },
      { id: 6, name: "Houmt Souk" },
      { id: 7, name: "Midoun" },
      { id: 8, name: "Ajim" },
      { id: 9, name: "Sidi Makhlouf" },
    ],
  },
  {
    id: 21,
    name: "Tataouine",
    delegations: [
      { id: 1, name: "Tataouine Nord" },
      { id: 2, name: "Tataouine Sud" },
      { id: 3, name: "Smar" },
      { id: 4, name: "Bir Lahmar" },
      { id: 5, name: "Ghomrassen" },
      { id: 6, name: "Dhehiba" },
      { id: 7, name: "Remada" },
    ],
  },
  {
    id: 22,
    name: "Gafsa",
    delegations: [
      { id: 1, name: "Gafsa Nord" },
      { id: 2, name: "Gafsa Sud" },
      { id: 3, name: "Sidi Aich" },
      { id: 4, name: "El Ksar" },
      { id: 5, name: "Oum El Araies" },
      { id: 6, name: "Redeyef" },
      { id: 7, name: "Metlaoui" },
      { id: 8, name: "Mdhila" },
      { id: 9, name: "El Guettar" },
      { id: 10, name: "Belkhir" },
      { id: 11, name: "Sned" },
    ],
  },
  {
    id: 23,
    name: "Tozeur",
    delegations: [
      { id: 1, name: "Tozeur" },
      { id: 2, name: "Degache" },
      { id: 3, name: "Tameghza" },
      { id: 4, name: "Nefta" },
      { id: 5, name: "Hazoua" },
    ],
  },
  {
    id: 24,
    name: "Kebili",
    delegations: [
      { id: 1, name: "Kebili Nord" },
      { id: 2, name: "Kebili Sud" },
      { id: 3, name: "Souk El Ahad" },
      { id: 4, name: "Douz Nord" },
      { id: 5, name: "Douz Sud" },
      { id: 6, name: "Faouar" },
    ],
  },
];

// Helper function to get governorate by ID
export const getGovernorateById = (id: number): Governorate | undefined => {
  return TUNISIA_GOVERNORATES.find((g) => g.id === id);
};

// Helper function to get governorate by name
export const getGovernorateByName = (name: string): Governorate | undefined => {
  const normalizedName = name.toLowerCase().trim();
  return TUNISIA_GOVERNORATES.find(
    (g) => g.name.toLowerCase() === normalizedName
  );
};

// Helper function to get delegations for a governorate
export const getDelegationsForGovernorate = (
  governorateId: number
): Delegation[] => {
  const governorate = getGovernorateById(governorateId);
  return governorate?.delegations || [];
};
